[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ReadMyDocs"
authors = [{name = "Alex", email = "hxszk@163.com"}]
dynamic = ["version", "description"]
